"""
Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

sum_of_numbers = 0
prev_number = 1
current_number = 1

# consider numbers below 4 million
while current_number < 4000000:
    # sum only even valued number
    if current_number % 2 == 0:
        sum_of_numbers += current_number

    next_number = prev_number + current_number
    prev_number = current_number
    current_number = next_number

print(sum_of_numbers)
